name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cmastudios
website: ${project.url}
main: ${main.class}
commands:
  setgroup:
    description: Set a player to a different group
    usage: /<command> <player> <group> [minutes]
    aliases: [chgrp, adduser]
    permission: cpermissions.control
permissions:
  cpermissions.control:
    description: Required in order to change player's ranks
